'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {message,mutate,request,type Paper,type Session,type Workspace} from '../../../lib/api';
type Detail={paper:Paper;reviews:{id:string;revision_id:string;reviewer_member_id:string;status:string;deadline?:string;reason?:string}[];comments:{id:string;revision_id:string;author_member_id:string;body:string;created_at:string}[]};
export function PapersPanel({workspace,session,onError}:{workspace:Workspace;session:Session;onError:(s:string)=>void}){const [papers,setPapers]=useState<Paper[]>([]);const [selected,setSelected]=useState<Detail|null>(null);const [busy,setBusy]=useState(false);const can=(p:string)=>session.permissions.includes('*')||session.permissions.includes(p);
 const refresh=useCallback(async()=>{try{const list=await request<{items:Paper[]}>(`/api/v1/papers?meeting_id=${workspace.meeting.id}`);setPapers(list.items);if(selected){const next=await request<Detail>(`/api/v1/papers/${selected.paper.id}`);setSelected(next)}}catch(e){onError(message(e))}},[workspace.meeting.id,selected?.paper.id]);
 useEffect(()=>{refresh()},[workspace.meeting.id]);
 async function post(path:string,data:Record<string,unknown>){setBusy(true);try{await mutate(path,session.csrf,data);await refresh()}catch(e){onError(message(e))}finally{setBusy(false)}}
 async function form(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();const node=e.currentTarget;const data=Object.fromEntries(new FormData(node));await post(path,data);node.reset()}
 async function upload(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);data.set('csrf',session.csrf);try{const response=await fetch(path,{method:'POST',credentials:'include',body:data,headers:{Accept:'text/html'}});if(!response.ok)throw new Error(`Upload failed (${response.status})`);await refresh();e.currentTarget.reset()}catch(err){onError(message(err))}finally{setBusy(false)}}
 return <section className="panel"><div className="section-heading"><div><h2>Board papers</h2><p>Revision-controlled drafting, review and immutable board-pack publication.</p></div><span>{busy?'Saving…':'Up to date'}</span></div><div className="paper-layout"><div><div className="cards">{papers.map(p=><button className={`paper-select ${selected?.paper.id===p.id?'selected':''}`} key={p.id} onClick={async()=>{try{setSelected(await request<Detail>(`/api/v1/papers/${p.id}`))}catch(e){onError(message(e))}}}><span><strong>{p.title}</strong><small>{p.agenda_title} · Revision {p.version_number}</small></span><span className="badge">{p.status.replaceAll('_',' ')}</span></button>)}</div>{papers.length===0&&<div className="empty">No workflow papers have been created.</div>}
 {can('papers.submit')&&<form className="work-form" onSubmit={e=>form(e,'/api/v1/papers')}><h3>New text-content paper draft</h3><div className="notice">This demonstrator stores the entered text as revision content. It is not a generated PDF.</div><input type="hidden" name="meeting_id" value={workspace.meeting.id}/><label>Agenda item<select name="agenda_item_id" required><option value="">Select item</option>{workspace.agenda.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{['title','purpose','background','recommendation','implications'].map(f=><label key={f}>{f[0].toUpperCase()+f.slice(1)}{f==='title'?<input name={f} required/>:<textarea name={f} required/>}</label>)}<label>Text revision content<textarea name="content" required/></label><button className="primary" disabled={busy}>Save draft</button></form>}</div>
 <aside>{selected&&<><h3>{selected.paper.title}</h3><p>Current revision <strong>{selected.paper.version_number}</strong> · {selected.paper.status.replaceAll('_',' ')}</p>{can('papers.submit')&&['draft','changes_requested'].includes(selected.paper.status)&&<div className="button-row"><button className="primary" onClick={()=>post(`/api/v1/papers/${selected.paper.id}/submit`,{revision_id:selected.paper.current_revision_id,lock_version:selected.paper.lock_version})}>Submit revision</button><button onClick={()=>{const content=prompt('Corrected text content for the next revision');if(content)post(`/api/v1/papers/${selected.paper.id}/revision`,{...selected.paper,revision_id:selected.paper.current_revision_id,content})}}>Create revision</button></div>}{can('papers.review')&&<form className="work-form" onSubmit={e=>form(e,`/api/v1/papers/${selected.paper.id}/reviewers`)}><h4>Assign reviewer</h4><label>Reviewer<select name="reviewer_member_id">{workspace.participants.map(p=><option key={p.member_id} value={p.member_id}>{p.display_name}</option>)}</select></label><label>Deadline<input name="deadline" type="datetime-local"/></label><button>Assign</button></form>}<form className="work-form" onSubmit={e=>form(e,`/api/v1/papers/${selected.paper.id}/comments`)}><h4>Revision comment</h4><input type="hidden" name="revision_id" value={selected.paper.current_revision_id}/><label>Comment<textarea name="body" required/></label><button>Add comment</button></form>{can('papers.review')&&<form className="work-form" onSubmit={e=>form(e,`/api/v1/papers/${selected.paper.id}/decision`)}><h4>Review decision</h4><input type="hidden" name="revision_id" value={selected.paper.current_revision_id}/><label>Decision<select name="decision"><option value="approved">Approve</option><option value="changes_requested">Request changes</option></select></label><label>Reason<input name="reason" required/></label><button>Record decision</button></form>}<h4>Reviews & comments</h4>{selected.reviews.map(r=><p key={r.id}><span className="badge">{r.status}</span> Revision {r.revision_id===selected.paper.current_revision_id?selected.paper.version_number:'earlier'} {r.reason&&`— ${r.reason}`}</p>)}{selected.comments.map(c=><blockquote key={c.id}>{c.body}<small>Revision {c.revision_id===selected.paper.current_revision_id?selected.paper.version_number:'earlier'}</small></blockquote>)}</>}
 {can('papers.publish')&&papers.some(p=>p.status==='approved')&&<button className="primary" onClick={()=>post('/api/v1/board-packs/publish',{meeting_id:workspace.meeting.id,paper_ids:papers.filter(p=>p.status==='approved').map(p=>p.id),label:`${workspace.meeting.title} board pack`})}>Publish approved papers as new edition</button>}</aside></div>
 <div className="document-zone"><Heading/><div className="cards">{workspace.documents.map(d=><article key={d.id}><h3>{d.title}</h3><p>{d.classification} · Version {d.version_number} · {Math.ceil(d.size_bytes/1024)} KB</p><div className="button-row"><a className="button" href={`/documents/${d.id}/download`}>Download</a>{can('documents.write')&&<form onSubmit={e=>upload(e,`/documents/${d.id}/replace`)}><input aria-label={`Replace ${d.title}`} name="file" type="file" accept="application/pdf,.pdf" required/><button>Replace file</button></form>}</div></article>)}</div>{can('documents.write')&&<form className="work-form" onSubmit={e=>upload(e,`/meetings/${workspace.meeting.id}/documents`)}><h3>Upload a real protected PDF</h3><label>Title<input name="title"/></label><label>Classification<select name="classification"><option>internal</option><option>confidential</option><option>public</option></select></label><label>Agenda item<select name="agenda_item_id"><option value="">None</option>{workspace.agenda.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label>PDF<input name="file" type="file" accept="application/pdf,.pdf" required/></label><button className="primary">Upload PDF</button></form>}</div></section>}
function Heading(){return <div className="section-heading"><div><h2>Protected documents</h2><p>Real multipart uploads and authenticated binary downloads.</p></div></div>}
