'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {AppShell} from '../components/session-shell';
import {EmptyState,Icon} from '../components/ui';
import {ApiError,getMeetings,getSession,getWorkspace,message,type Meeting,type Session,type Workspace} from '../lib/api';
const fd=(d:string)=>new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short'}).format(new Date(d)).split(' ');const ft=(d:string)=>new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(d));
export default function Home(){const router=useRouter();const [session,setSession]=useState<Session|null>(null);const [meetings,setMeetings]=useState<Meeting[]>([]);const [spaces,setSpaces]=useState<Workspace[]>([]);const [error,setError]=useState('');
 useEffect(()=>{Promise.all([getSession(),getMeetings()]).then(async([s,m])=>{setSession(s);setMeetings(m.items);setSpaces(await Promise.all(m.items.map(x=>getWorkspace(x.id))))}).catch(e=>{if(e instanceof ApiError&&e.status===401)router.replace('/login');else setError(message(e))})},[router]);
 const data=useMemo(()=>{const documents=spaces.flatMap(x=>x.documents.map(d=>({...d,meeting:x.meeting})));const actions=spaces.flatMap(x=>x.actions.map(a=>({...a,meeting:x.meeting})));return{documents,actions,upcoming:meetings.filter(x=>new Date(x.starts_at)>=new Date()&&x.status!=='completed'),overdue:actions.filter(x=>x.is_overdue&&x.status!=='completed'),decisions:spaces.flatMap(x=>x.resolutions.map(r=>({...r,meeting:x.meeting}))) }},[meetings,spaces]);
 if(!session&&!error)return <main className="center loading-state" aria-busy="true"><span className="spinner"/>Preparing your board portal…</main>;if(!session)return <main className="center"><div className="alert error">{error}<button onClick={()=>location.reload()}>Retry</button></div></main>;
 return <AppShell session={session}><main className="dashboard"><header className="page-heading"><div><p className="eyebrow">Board workspace</p><h1>Welcome back, {session.member.display_name.split(' ')[0]}</h1><p>Here is what needs your attention across your accessible meetings.</p></div></header>{error&&<div role="alert" className="alert error">{error}<button onClick={()=>location.reload()}>Retry</button></div>}
 <section className="summary-grid" aria-label="Accessible meeting summary"><Summary icon="calendar" value={data.upcoming.length} label="Upcoming meetings" href="#meetings" tone="blue"/><Summary icon="document" value={data.documents.length} label="Board documents" href="#documents" tone="teal"/><Summary icon="check" value={data.actions.filter(x=>x.status!=='completed'&&x.owner_member_id===session.member.id).length} label="My open actions" href="#actions" tone="green"/><Summary icon="clock" value={data.overdue.filter(x=>x.owner_member_id===session.member.id).length} label="My overdue actions" href="#actions" tone="amber"/></section><p className="scope-note">Counts reflect all meetings and records currently accessible to you.</p>
 <div className="dashboard-grid"><section className="surface meetings-panel" id="meetings"><Head title="Upcoming meetings"/><div className="meeting-list">{data.upcoming.slice(0,4).map((m,i)=><article className={i===0?'featured':''} key={m.id}><time dateTime={m.starts_at}><strong>{fd(m.starts_at)[0]}</strong><span>{fd(m.starts_at)[1]}</span></time><div className="row-main"><span className={`badge ${m.status}`}>{m.status}</span><h3>{m.title}</h3><p><Icon name="clock" size={15}/>{ft(m.starts_at)} <span>·</span> {m.location||'Location to be confirmed'}</p></div><Link className="button row-action" href={`/meetings/${m.id}`}>Open meeting <Icon name="arrow" size={16}/></Link></article>)}</div>{!data.upcoming.length&&<EmptyState title="No upcoming meetings">New meetings will appear here when scheduled.</EmptyState>}</section>
 <section className="surface" id="documents"><Head title="Recent board documents"/><div className="compact-list">{data.documents.slice(0,5).map(d=><article key={d.id}><span className="file-icon"><Icon name="document"/></span><div><h3>{d.title}</h3><p>{d.classification} · Revision {d.version_number}</p></div><a className="icon-button" href={`/documents/${d.id}/download`} aria-label={`Download ${d.title}`}>↓</a></article>)}</div>{!data.documents.length&&<EmptyState title="No documents available">Meeting papers you can access will appear here.</EmptyState>}</section>
 <section className="surface" id="actions"><Head title="My action items"/><div className="compact-list action-list">{data.actions.filter(a=>a.owner_member_id===session.member.id).slice(0,5).map(a=><article key={a.id}><span className={`task-dot ${a.status}`}/><div><h3>{a.description}</h3><p>{a.due_at?`Due ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(a.due_at))}`:'No due date'} · {a.priority}</p></div><span className={`badge ${a.is_overdue?'overdue':a.status}`}>{a.is_overdue?'Overdue':a.status.replaceAll('_',' ')}</span></article>)}</div>{!data.actions.some(a=>a.owner_member_id===session.member.id)&&<EmptyState title="You have no assigned actions">Assigned follow-up items will appear here.</EmptyState>}</section>
 <section className="surface decisions-panel" id="decisions"><Head title="Recent decisions"/><div className="compact-list">{data.decisions.slice(0,4).map(r=><article key={r.id}><span className="file-icon decision"><Icon name="decision"/></span><div><h3>{r.text}</h3><p>{r.meeting.title} · {r.outcome.replaceAll('_',' ')}</p></div><span className={`badge ${r.status}`}>{r.status}</span></article>)}</div>{!data.decisions.length&&<EmptyState title="No decisions recorded">Approved resolutions will be collected here.</EmptyState>}</section></div></main></AppShell>}
function Summary({icon,value,label,href,tone}:{icon:string;value:number;label:string;href:string;tone:string}){return <a className="summary-card" href={href}><span className={`summary-icon ${tone}`}><Icon name={icon}/></span><span><strong>{value}</strong><small>{label}</small></span></a>}function Head({title}:{title:string}){return <div className="panel-heading"><h2>{title}</h2></div>}
